const express = require('express')
const router = express.Router()
const controller = require('../../controllers/payment/voucher.controller')
const upload = require('../../middlewares/multer.middleware')
const {voucherSchema} = require("../../validates/voucher.validate")
const {validate} = require('../../middlewares/validate.middleware')
const { authenticationPartner } = require('../../middlewares/authentication.middleware')
router.post('/add-voucher',authenticationPartner,upload.single('image'),validate(voucherSchema),controller.addVoucher)
router.delete('/delete-voucher',authenticationPartner,controller.deleteVoucher)
router.put('/edit-voucher',authenticationPartner,upload.single('image'),validate(voucherSchema),controller.editVoucher)

router.get('/get-vouchers',authenticationPartner,controller.getVouchersPartner)
router.get('/get-voucher-details',authenticationPartner,controller.getVoucher)
router.get('/get-vouchers-partner',controller.getVouchersPayment)
module.exports = router